import { DEFAULT_PAGE_CONFIG, type ComponentSchema, type TemplateSchema } from '@ptd/core'

const UI_FONT = "'Sarasa UI SC', 'Microsoft YaHei UI', sans-serif"
const SERIF_FONT = "'Noto Serif SC', 'Source Han Serif SC', serif"

function component(
  id: string,
  type: ComponentSchema['component'],
  name: string,
  propValue: unknown,
  style: ComponentSchema['style'],
  group: ComponentSchema['group'] = 'common',
): ComponentSchema {
  return {
    id,
    component: type,
    name,
    code: type,
    group,
    propValue,
    style,
    groupStyle: {},
    position: { x: style.left, y: style.top },
  }
}

export const DEMO_TEMPLATE_TITLE = '华东区域电价预测周报 · 示例'

export const DEMO_TEMPLATE: TemplateSchema = {
  _version: 1,
  pageConfig: {
    ...DEFAULT_PAGE_CONFIG,
    pageSize: 'A4',
    pageDirection: 'p',
    pageLayout: 'fixed',
    pageWidth: 210,
    pageHeight: 297,
    pageCurHeight: 297,
    pageMarginTop: 8,
    pageMarginRight: 8,
    pageMarginBottom: 8,
    pageMarginLeft: 8,
    title: DEMO_TEMPLATE_TITLE,
    background: '#ffffff',
    color: '#232321',
    fontFamily: UI_FONT,
  },
  pages: [
    {
      id: 'demo-page-1',
      componentData: [
        component('demo-header-rule', 'RoyRect', '报告页眉', null, {
          left: 58,
          top: 48,
          width: 678,
          height: 78,
          rotate: 0,
          opacity: 1,
          background: '#242422',
          borderWidth: 0,
          borderType: 'solid',
          borderColor: '#242422',
          borderRadius: '0',
        }),
        component('demo-kicker', 'RoySimpleText', '报告类型', 'POWER MARKET / WEEK 32', {
          left: 82,
          top: 64,
          width: 280,
          height: 18,
          rotate: 0,
          opacity: 1,
          color: '#c7c7c2',
          fontFamily: UI_FONT,
          fontSize: 8,
          fontWeight: '700',
          letterSpacing: '1.4px',
        }),
        component('demo-title', 'RoySimpleText', '报告标题', '华东区域电价预测周报', {
          left: 82,
          top: 86,
          width: 430,
          height: 32,
          rotate: 0,
          opacity: 1,
          color: '#fafaf7',
          fontFamily: SERIF_FONT,
          fontSize: 22,
          fontWeight: '700',
        }),
        component('demo-period', 'RoySimpleText', '预测周期', '2026.08.03—08.09', {
          left: 530,
          top: 88,
          width: 180,
          height: 22,
          rotate: 0,
          opacity: 1,
          color: '#fafaf7',
          fontFamily: UI_FONT,
          fontSize: 10,
          fontWeight: '600',
          justifyContent: 'flex-end',
        }),
        component('demo-summary-label', 'RoySimpleText', '摘要标签', '本周判断', {
          left: 82,
          top: 164,
          width: 90,
          height: 20,
          rotate: 0,
          opacity: 1,
          color: '#6d6d68',
          fontFamily: UI_FONT,
          fontSize: 9,
          fontWeight: '700',
        }),
        component(
          'demo-summary',
          'RoyText',
          '市场摘要',
          '<p><strong>午间光伏出力抬升，现货价格中枢预计环比回落 3.8%。</strong></p><p>周三起华东大部高温回升，晚高峰负荷增量将抵消部分新能源供给。建议零售组合维持中性敞口，并将周五 18:00—21:00 作为重点风险窗口。</p>',
          {
            left: 82,
            top: 190,
            width: 628,
            height: 112,
            rotate: 0,
            opacity: 1,
            color: '#292927',
            fontFamily: SERIF_FONT,
            fontSize: 12,
            lineHeight: '1.75',
          },
        ),
        component('demo-metric-bg', 'RoyRect', '指标底框', null, {
          left: 82,
          top: 330,
          width: 628,
          height: 118,
          rotate: 0,
          opacity: 1,
          background: '#f1f1ed',
          borderWidth: 0,
          borderType: 'solid',
          borderColor: '#d8d8d2',
          borderRadius: '0',
        }),
        component(
          'demo-metrics',
          'RoyText',
          '核心指标',
          '<p><strong>均价预测</strong>　392.6 元/MWh　　　　<strong>峰谷价差</strong>　286.4 元/MWh</p><p><strong>负荷峰值</strong>　312.8 GW　　　　　　<strong>新能源占比</strong>　31.7%</p><p><strong>模型区间</strong>　P10 348.2　/　P90 461.8 元/MWh</p>',
          {
            left: 106,
            top: 350,
            width: 580,
            height: 82,
            rotate: 0,
            opacity: 1,
            color: '#353531',
            fontFamily: UI_FONT,
            fontSize: 10,
            lineHeight: '1.9',
          },
        ),
        component('demo-table-head', 'RoyRect', '时段表头', null, {
          left: 82,
          top: 488,
          width: 628,
          height: 34,
          rotate: 0,
          opacity: 1,
          background: '#343431',
          borderWidth: 0,
          borderType: 'solid',
          borderColor: '#343431',
          borderRadius: '0',
        }),
        component(
          'demo-table-label',
          'RoySimpleText',
          '时段表头文字',
          '时段　　　　价格区间（元/MWh）　　　　供需判断　　　　　　策略',
          {
            left: 100,
            top: 497,
            width: 590,
            height: 18,
            rotate: 0,
            opacity: 1,
            color: '#fafaf7',
            fontFamily: UI_FONT,
            fontSize: 9,
            fontWeight: '700',
          },
        ),
        component(
          'demo-table-body',
          'RoyText',
          '分时预测',
          '<p>00:00—06:00　　　326—372　　　　　　　风电偏强　　　　　　低位采购</p><p>06:00—11:00　　　368—426　　　　　　　负荷爬坡　　　　　　分批锁定</p><p>11:00—16:00　　　248—338　　　　　　　光伏高位　　　　　　控制长仓</p><p>16:00—21:00　　　438—562　　　　　　　晚峰趋紧　　　　　　重点对冲</p><p>21:00—24:00　　　354—418　　　　　　　供需回落　　　　　　恢复中性</p>',
          {
            left: 99,
            top: 540,
            width: 592,
            height: 224,
            rotate: 0,
            opacity: 1,
            color: '#30302d',
            fontFamily: UI_FONT,
            fontSize: 10,
            lineHeight: '2.25',
          },
        ),
        component('demo-table-border', 'RoyRect', '时段表格外框', null, {
          left: 82,
          top: 522,
          width: 628,
          height: 260,
          rotate: 0,
          opacity: 1,
          background: 'transparent',
          borderWidth: 1,
          borderType: 'solid',
          borderColor: '#bdbdb7',
          borderRadius: '0',
        }),
        component(
          'demo-risk',
          'RoyText',
          '风险提示',
          '<p><strong>风险提示</strong>　气象预报偏差、跨区通道临时检修与机组非计划停运，可能使实际价格突破模型置信区间。本报告为设计演示数据，不构成交易建议。</p>',
          {
            left: 82,
            top: 826,
            width: 628,
            height: 76,
            rotate: 0,
            opacity: 1,
            color: '#555550',
            fontFamily: UI_FONT,
            fontSize: 9,
            lineHeight: '1.65',
          },
        ),
        component(
          'demo-footer',
          'RoySimpleText',
          '页脚',
          'Foliq · 电力市场分析示例　　　　　　　　　　　　　01',
          {
            left: 82,
            top: 1018,
            width: 628,
            height: 18,
            rotate: 0,
            opacity: 1,
            color: '#777771',
            fontFamily: UI_FONT,
            fontSize: 8,
            letterSpacing: '0.5px',
          },
        ),
      ],
    },
  ],
  dataSource: [],
  dataSet: {},
}
