import type { ComponentSchema, TemplateSchema } from '@ptd/react-designer'

const UI_FONT = "'Sarasa UI SC', 'Microsoft YaHei UI', sans-serif"
const SERIF_FONT = "'Noto Serif SC', 'Source Han Serif SC', serif"

function component(
  id: string,
  type: ComponentSchema['component'],
  name: string,
  propValue: unknown,
  style: ComponentSchema['style'],
  group: ComponentSchema['group'] = 'common',
): ComponentSchema {
  return {
    id,
    component: type,
    name,
    code: type,
    group,
    propValue,
    style,
    groupStyle: {},
    position: { x: style.left, y: style.top },
  }
}

export const INITIAL_TEMPLATE: TemplateSchema = {
  _version: 1,
  pageConfig: {
    pageSize: 'A4',
    pageDirection: 'p',
    pageLayout: 'fixed',
    pageWidth: 210,
    pageHeight: 297,
    pageCurHeight: 297,
    pageMarginBottom: 10,
    pageMarginTop: 10,
    pageMarginLeft: 10,
    pageMarginRight: 10,
    title: '新建模板',
    scale: 1,
    background: '#fcfdff',
    color: '#1d2735',
    fontSize: 12,
    fontFamily: SERIF_FONT,
    lineHeight: 1.4,
  },
  pages: [{ id: 'page-1', componentData: [] }],
  dataSource: [],
  dataSet: {},
}

/**
 * A deterministic real document used only by the DEV product capture route.
 * It deliberately uses the same schema and renderers as ordinary documents.
 */
export const PRODUCT_CAPTURE_TEMPLATE: TemplateSchema = {
  _version: 1,
  pageConfig: {
    pageSize: 'custom',
    pageDirection: 'p',
    pageLayout: 'fixed',
    pageWidth: 148,
    pageHeight: 210,
    pageCurHeight: 210,
    pageMarginBottom: 8,
    pageMarginTop: 8,
    pageMarginLeft: 8,
    pageMarginRight: 8,
    title: '冷链出库标签 · 华东 07',
    scale: 1,
    background: '#fcfdff',
    color: '#1d2735',
    fontSize: 10,
    fontFamily: UI_FONT,
    lineHeight: 1.35,
  },
  pages: [
    {
      id: 'capture-page-1',
      componentData: [
        component(
          'capture-band',
          'RoyRect',
          '标题底色',
          null,
          {
            left: 31,
            top: 34,
            width: 496,
            height: 76,
            rotate: 0,
            opacity: 1,
            background: '#1d2735',
            borderWidth: 0,
            borderType: 'solid',
            borderColor: '#1d2735',
            borderRadius: '0',
          },
          'shape',
        ),
        component('capture-kicker', 'RoySimpleText', '业务类型', 'OUTBOUND / 冷链出库', {
          left: 50,
          top: 45,
          width: 230,
          height: 22,
          rotate: 0,
          opacity: 1,
          color: '#b9c9e8',
          fontFamily: UI_FONT,
          fontSize: 9,
          fontWeight: '600',
          letterSpacing: '1.2px',
        }),
        component('capture-title', 'RoySimpleText', '标签标题', '华东冷链出库标签', {
          left: 50,
          top: 68,
          width: 330,
          height: 34,
          rotate: 0,
          opacity: 1,
          color: '#f8fafc',
          fontFamily: SERIF_FONT,
          fontSize: 22,
          fontWeight: '600',
          letterSpacing: '0.4px',
        }),
        component('capture-proof', 'RoySimpleText', '校样标记', '已校样', {
          left: 435,
          top: 57,
          width: 72,
          height: 31,
          rotate: 0,
          opacity: 1,
          color: '#f8fafc',
          background: '#c84f3e',
          fontFamily: UI_FONT,
          fontSize: 11,
          fontWeight: '600',
          justifyContent: 'center',
          alignItems: 'center',
          padding: '6px 8px',
        }),
        component('capture-order-label', 'RoySimpleText', '订单标签', '出库单号', {
          left: 50,
          top: 135,
          width: 90,
          height: 22,
          rotate: 0,
          opacity: 1,
          color: '#627084',
          fontFamily: UI_FONT,
          fontSize: 9,
          fontWeight: '600',
        }),
        component('capture-order', 'RoySimpleText', '订单编号', 'PTD-20260731-0842', {
          left: 50,
          top: 158,
          width: 290,
          height: 34,
          rotate: 0,
          opacity: 1,
          color: '#1d2735',
          fontFamily: UI_FONT,
          fontSize: 19,
          fontWeight: '600',
          letterSpacing: '0.5px',
        }),
        component(
          'capture-qr',
          'RoyQRCode',
          '追溯二维码',
          {
            text: 'https://ptd.dev/trace/PTD-20260731-0842',
            colorDark: '#1d2735',
            colorLight: '#ffffff',
            correctLevel: 'M',
            margin: 2,
          },
          { left: 409, top: 130, width: 98, height: 98, rotate: 0, opacity: 1 },
        ),
        component(
          'capture-rule-1',
          'RoyLine',
          '分隔线',
          null,
          {
            left: 50,
            top: 213,
            width: 328,
            height: 1,
            rotate: 0,
            opacity: 1,
            background: '#b8c2ce',
          },
          'shape',
        ),
        component('capture-destination-label', 'RoySimpleText', '目的地标签', '目的地', {
          left: 50,
          top: 237,
          width: 74,
          height: 22,
          rotate: 0,
          opacity: 1,
          color: '#627084',
          fontFamily: UI_FONT,
          fontSize: 9,
          fontWeight: '600',
        }),
        component('capture-destination', 'RoySimpleText', '目的地', '上海 · 浦东新区', {
          left: 50,
          top: 260,
          width: 230,
          height: 30,
          rotate: 0,
          opacity: 1,
          color: '#1d2735',
          fontFamily: SERIF_FONT,
          fontSize: 17,
          fontWeight: '600',
        }),
        component('capture-route-label', 'RoySimpleText', '路由标签', '路线 / 温区', {
          left: 310,
          top: 237,
          width: 90,
          height: 22,
          rotate: 0,
          opacity: 1,
          color: '#627084',
          fontFamily: UI_FONT,
          fontSize: 9,
          fontWeight: '600',
        }),
        component('capture-route', 'RoySimpleText', '路由', 'HD-07  /  2–8°C', {
          left: 310,
          top: 260,
          width: 197,
          height: 30,
          rotate: 0,
          opacity: 1,
          color: '#1d2735',
          fontFamily: UI_FONT,
          fontSize: 14,
          fontWeight: '600',
        }),
        component(
          'capture-note-box',
          'RoyRect',
          '操作说明底框',
          null,
          {
            left: 50,
            top: 316,
            width: 457,
            height: 116,
            rotate: 0,
            opacity: 1,
            background: '#f2f5f8',
            borderWidth: 1,
            borderType: 'solid',
            borderColor: '#c8d0da',
            borderRadius: '0',
          },
          'shape',
        ),
        component(
          'capture-note',
          'RoyText',
          '操作说明',
          '<p><strong>操作提示</strong></p><p>到货后请立即核验箱体温度与封签编号。异常件进入复核区，不得直接入库。</p>',
          {
            left: 68,
            top: 331,
            width: 420,
            height: 84,
            rotate: 0,
            opacity: 1,
            color: '#334154',
            fontFamily: UI_FONT,
            fontSize: 10,
            lineHeight: '1.5',
          },
        ),
        component(
          'capture-barcode',
          'RoyBarCode',
          '出库条形码',
          {
            text: 'PTD202607310842',
            bcid: 'code128',
            colorDark: '#1d2735',
            includeText: true,
          },
          { left: 72, top: 474, width: 413, height: 88, rotate: 0, opacity: 1 },
        ),
        component(
          'capture-footer-rule',
          'RoyLine',
          '页脚分隔线',
          null,
          {
            left: 50,
            top: 596,
            width: 457,
            height: 1,
            rotate: 0,
            opacity: 1,
            background: '#b8c2ce',
          },
          'shape',
        ),
        component('capture-footer', 'RoySimpleText', '页脚', '打印模板设计器 · 版本化校样', {
          left: 50,
          top: 618,
          width: 240,
          height: 22,
          rotate: 0,
          opacity: 1,
          color: '#627084',
          fontFamily: UI_FONT,
          fontSize: 9,
          letterSpacing: '0.6px',
        }),
        component('capture-page-number', 'RoySimpleText', '页码', '01 / 02', {
          left: 435,
          top: 618,
          width: 72,
          height: 22,
          rotate: 0,
          opacity: 1,
          color: '#334154',
          fontFamily: UI_FONT,
          fontSize: 9,
          fontWeight: '600',
          justifyContent: 'flex-end',
        }),
      ],
    },
    {
      id: 'capture-page-2',
      componentData: [
        component('capture-page-2-title', 'RoySimpleText', '复核记录', '出库复核记录', {
          left: 50,
          top: 50,
          width: 300,
          height: 40,
          rotate: 0,
          opacity: 1,
          color: '#1d2735',
          fontFamily: SERIF_FONT,
          fontSize: 22,
          fontWeight: '600',
        }),
      ],
    },
  ],
  dataSource: [],
  dataSet: {},
}
