export type {
  PageConfig,
  PageSize,
  PageDirection,
  PageLayout,
  ComponentSchema,
  ComponentStyle,
  ComponentPosition,
  ComponentType,
  CreatableComponentType,
  ComponentCategory,
  ComponentCatalogGroup,
  ComponentMaturity,
  ComponentCreationMode,
  DataSourceField,
  DataFieldType,
  DataSet,
  BindingExpression,
  ComponentBinding,
  ComponentBindingTarget,
  ComponentBindingTargetDefinition,
  DataDiagnostic,
  DataDiagnosticCode,
  DataDiagnosticSeverity,
  DataFieldDefinition,
  DataFormatter,
  DataPath,
  DataPathArrayItem,
  DataPathSegment,
  DataRecord,
  DataSourceLimits,
  DataValueType,
  FieldBindingExpression,
  JsonObject,
  JsonPrimitive,
  JsonValue,
  LiteralBindingSegment,
  RenderContext,
  RenderMode,
  TemplateDataDefinition,
  TextBindingExpression,
  TemplateSchema,
  TemplatePage,
  TemplateOutputDefinition,
  PageMaster,
  PageMasterRegion,
  OutputBounds,
  OutputDiagnostic,
  OutputDiagnosticCode,
  OutputDiagnosticSeverity,
  OutputDocument,
  OutputFragment,
  OutputFragmentContinuation,
  OutputOptions,
  OutputPage,
  OutputPageContext,
  OutputRegion,
  OutputRegionKind,
  BarCodeFormat,
  BarCodeProps,
  ImageFit,
  ImagePosition,
  ImageProps,
  QRCodeErrorCorrection,
  QRCodeProps,
  SimpleTableCell,
  DetailTableColumn,
  DetailTableFooter,
  DetailTableFooterCell,
  DetailTableProps,
  SimpleTableProps,
  TableBorderStyle,
  TableCellRange,
  TableCellStyle,
  TableCellTextDecoration,
  TableHorizontalAlign,
  TableVerticalAlign,
} from './types'
export {
  BAR_CODE_FORMATS,
  DEFAULT_BAR_CODE_PROPS,
  DEFAULT_IMAGE_PROPS,
  DEFAULT_PAGE_CONFIG,
  normalizePageConfig,
  pageConfigError,
  DEFAULT_QR_CODE_PROPS,
  barCodeContentError,
  imageSourceError,
  isBarCodeProps,
  isImageProps,
  isQRCodeProps,
  normalizeBarCodeProps,
  normalizeImageProps,
  normalizeQRCodeProps,
  qrCodeContentError,
  DEFAULT_SIMPLE_TABLE_PROPS,
  DEFAULT_DETAIL_TABLE_PROPS,
  DEFAULT_TABLE_CELL_STYLE,
  createSimpleTableProps,
  deleteTableColumn,
  deleteTableRow,
  expandTableCellRange,
  getTableCellAt,
  getTableCellBounds,
  getTableCellIdsInRange,
  insertTableColumn,
  insertTableRow,
  isSimpleTableProps,
  mergeTableCells,
  normalizeSimpleTableProps,
  isDetailTableProps,
  normalizeDetailTableProps,
  normalizeTableCellRange,
  resizeTableColumn,
  resizeTableRow,
  splitTableCell,
  updateTableCellText,
  updateTableCellsStyle,
  DATA_SOURCE_LIMITS,
  OUTPUT_PAGE_TOKENS,
} from './types'

export { PAGE_SIZES, COMMON_SCALE, AUTO_PAGE_COMPONENTS } from './constants'
export type { PageSizeDefinition } from './constants'

export {
  MEASUREMENT_UNIT_DEFINITIONS,
  convertMeasurement,
  formatMeasurement,
  fromDisplayMeasurement,
  getMeasurementStep,
  getPageDimensions,
  getPageSizeDimensions,
  mmToPx,
  parseMeasurement,
  pxToMm,
  snapMeasurement,
  toDisplayMeasurement,
} from './utils'
export type {
  FormatMeasurementOptions,
  MeasurementStepMode,
  MeasurementUnit,
  MeasurementUnitDefinition,
  PageDimensions,
} from './utils'

export {
  ARRAY_ITEM_PATH_SEGMENT,
  DataBindingEngine,
  canonicalizeTemplateData,
  convertByType,
  dataFieldIdForPath,
  evaluateBinding,
  flattenDataFields,
  formatDataPath,
  formatDataValue,
  inferDataDefinition,
  isDataPath,
  isDataPathArrayItem,
  isSafeDataKey,
  normalizeTemplateData,
  parseDataPath,
  parseLegacyBindingExpression,
  parseRuntimeRecordsJson,
  readDataPath,
  renderContextError,
  resolveComponentBindings,
  validateRuntimeRecords,
} from './data-binding'
export type {
  BindingEvaluationResult,
  ComponentBindingResolution,
  DataPathParseResult,
  DataPathReadResult,
  NormalizedTemplateData,
  RuntimeRecordsSummary,
  RuntimeRecordsValidationResult,
} from './data-binding'

export { ComponentRegistry, defaultRegistry, getComponentBindingTargets } from './registry'
export type {
  CatalogComponentDefinition,
  ComponentCatalogMetadata,
  ComponentDefinition,
} from './registry'

export {
  CURRENT_TEMPLATE_VERSION,
  TEMPLATE_SCHEMA_JSON_LIMIT_BYTES,
  serialize,
  deserialize,
} from './serialization'
export { isTemplateSchema } from './schema-validation'
