name: GitHub Actions Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Install and Build
        run: |
          npm install
          npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.PRINT-TEMPLATE-DESIGNER-TOKEN }}
          BRANCH: master
          FOLDER: dist
          CLEAN: true
          REPOSITORY_NAME: royians/royians.github.io
          TARGET_FOLDER: print-template-designer
