name: 🔀 Sync mirror to Gitee Repo

on:
  push:
    branches:
      - feature-1.0.0
      - master
      - preview
      - feature-0.0.0
  create:

jobs:
  mirror:
    runs-on: ubuntu-latest
    if: github.repository == 'ROYIANS/print-template-designer'
    steps:
      - name: mirror
        continue-on-error: true
        if: github.event_name == 'push' || (github.event_name == 'create' && github.event.ref_type == 'tag')
        uses: wearerequired/git-mirror-action@v1.2.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
        with:
          source-repo: 'git@github.com:ROYIANS/print-template-designer.git'
          destination-repo: 'git@gitee.com:ROYIANS/print-template-designer.git'